const poemData = [
    { text: "齐宣王", py: "qí xuān wáng", zh: "齐国国君（齐宣王），喜欢听大合奏。", en: "King Xuan of Qi" },
    { text: "使", py: "shǐ", zh: "动词，命令，让，派遣。", en: "ordered", exam: true },
    { text: "人", py: "rén", zh: "乐师，吹竽的人。", en: "people to" },
    { text: "吹竽", py: "chuī yú", zh: "吹奏“竽”（古代一种竹制的管乐器）。", en: "play the yu," },
    { text: "，", punc: true },
    { text: "必", py: "bì", zh: "副词，一定，每次都必须。", en: "and it must be" },
    { text: "三百人", py: "sān bǎi rén", zh: "三百人一起大合奏。", en: "three hundred people together." },
    { text: "。", punc: true },
    { text: "南郭处士", py: "nán guō chǔ shì", zh: "南郭先生。“处士”指有才德但没有做官的读书人，这里带讽刺意味。", en: "Mr. Nanguo" },
    { text: "请", py: "qǐng", zh: "动词，请求，主动申请。", en: "asked", exam: true },
    { text: "为", py: "wèi", zh: "介词，给，替。", en: "to play for" },
    { text: "王", py: "wáng", zh: "齐宣王。", en: "the king," },
    { text: "吹竽", py: "chuī yú", zh: "吹竽。", en: "playing the yu." },
    { text: "，", punc: true },
    { text: "宣王", py: "xuān wáng", zh: "齐宣王。", en: "King Xuan" },
    { text: "说", py: "yuè", zh: "通假字，同“悦”，喜欢，高兴。", en: "was pleased", exam: true },
    { text: "之", py: "zhī", zh: "代词，指代南郭先生这件事。", en: "with him," },
    { text: "，", punc: true },
    { text: "廪食", py: "lǐn sì", zh: "动词词组，廪（lǐn）是粮仓，食（sì）是给……吃。意思是官府供给粮食、发给薪水。", en: "and fed him with royal meals", exam: true },
    { text: "以", py: "yǐ", zh: "介词，按照，等同于。", en: "just like" },
    { text: "数百人", py: "shù bǎi rén", zh: "其他几百个正规乐师的待遇。", en: "the other hundreds of musicians." },
    { text: "。", punc: true },
    { text: "宣王", py: "xuān wáng", zh: "齐宣王。", en: "King Xuan" },
    { text: "死", py: "sǐ", zh: "去世，驾崩。", en: "died," },
    { text: "，", punc: true },
    { text: "湣王", py: "mǐn wáng", zh: "齐湣（mǐn）王，齐宣王的儿子，喜欢听独奏。", en: "King Min" },
    { text: "立", py: "lì", zh: "动词，继承王位，登基。", en: "became the new king." },
    { text: "，", punc: true },
    { text: "好", py: "hào", zh: "动词，喜欢，喜好。", en: "He liked", exam: true },
    { text: "一一", py: "yī yī", zh: "副词，一个接一个地，单独地。", en: "to listen to them one by one," },
    { text: "听", py: "tīng", zh: "听。", en: "listening to" },
    { text: "之", py: "zhī", zh: "代词，他们（指乐师们）。", en: "them play solo," },
    { text: "，", punc: true },
    { text: "处士", py: "chǔ shì", zh: "南郭先生。", en: "so Mr. Nanguo" },
    { text: "逃", py: "táo", zh: "动词，逃跑，溜走。", en: "ran away." },
    { text: "。", punc: true }
];
